# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6637484d7506a9d83ad396c485cf8cdc5241ad113f8eb86e8275128c04d62562c1c75dc7e8336e6de5e8db392cd212fb1c96e06d828cefe3ae583cbe0701dc5b

test:
  secret_key_base: 937d5c8cf0796ad235de3bdf414c3678e2edd2a123b82482b56b33d62ec33ee4cd37d3d016186695e23bbee993ed2a3aca52e67ae6a4ccbcfd6dccceda8cfd38

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
